name: Clang Build, Lint and Test
on: [push]
jobs:
  Clang-Build-Lint-Test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Build and Lint
        run: |
          cmake --preset=clang-debug .
          cmake --build --preset=clang-debug
      - name: Test
        run: |
          ctest --preset=default
