name: GCC Build and Test
on: [push]
jobs:
  GCC-Build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cmake --preset=gcc-debug-no-clang-tidy .
          cmake --build --preset=gcc-debug-no-clang-tidy
      - name: Test
        run: |
          ctest --preset=default
